# Generated by Django 3.1.4 on 2020-12-14 10:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesmodel',
            name='date_create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
